# Generated by Django 3.2.7 on 2022-11-22 17:52

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='YouTube.IM/%Y/%m')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('web_site', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SendMail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('message', models.TextField(blank=True, null=True)),
                ('phone_number', models.CharField(max_length=255)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(verbose_name='название')),
                ('organization', models.CharField(max_length=50, verbose_name='организация')),
                ('video', models.FileField(blank=True, null=True, upload_to='upload_location', verbose_name='видео')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='дата создания')),
                ('published_date', models.DateTimeField(blank=True, null=True, verbose_name='дата публикации')),
                ('organization1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='Devapp.organization')),
            ],
            options={
                'verbose_name': 'Видео',
                'verbose_name_plural': 'Видео',
            },
        ),
        migrations.CreateModel(
            name='Vacancies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=50, verbose_name='компания')),
                ('job_title', models.CharField(max_length=50, verbose_name='тип')),
                ('salary', models.TextField(verbose_name='должность')),
                ('type_of', models.CharField(choices=[('USD', 'USD'), ('KGS', 'KGS'), ('RUB', 'RUB')], max_length=50, verbose_name='валюта')),
                ('type_of_2', models.CharField(max_length=50, verbose_name='оклад')),
                ('description', models.TextField(verbose_name='описание')),
                ('email', models.EmailField(blank=True, max_length=50, verbose_name='E-mail')),
                ('organization2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacancies', to='Devapp.organization')),
            ],
            options={
                'verbose_name': 'Вакансия',
                'verbose_name_plural': 'Вакансии',
            },
        ),
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(verbose_name='название')),
                ('when', models.DateTimeField(blank=True, null=True, verbose_name='когда')),
                ('organizer', models.CharField(max_length=20, verbose_name='организатор')),
                ('location', models.TextField(verbose_name='локация')),
                ('description', models.TextField(blank=True, verbose_name='описание')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='Devapp.organization')),
            ],
            options={
                'verbose_name': 'Мероприятие',
                'verbose_name_plural': 'Мероприятия',
            },
        ),
    ]
