# Generated by Django 3.2.7 on 2022-08-16 11:22

import Devapp.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('when', models.TextField()),
                ('organizer', models.CharField(max_length=20)),
                ('location', models.TextField()),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Мероприятие',
                'verbose_name_plural': 'Мероприятия',
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='YouTube.IM/%Y/%m')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('web_site', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('date', models.CharField(max_length=50)),
                ('organization', models.CharField(max_length=50)),
                ('video', models.FileField(blank=True, null=True, upload_to=Devapp.models.upload_location)),
            ],
            options={
                'verbose_name': 'Видео',
                'verbose_name_plural': 'Видео',
            },
        ),
        migrations.CreateModel(
            name='Vacancies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=50)),
                ('job_title', models.CharField(max_length=50)),
                ('salary', models.TextField()),
                ('type_of', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('email', models.EmailField(blank=True, max_length=50)),
                ('vacancies', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacancies', to='Devapp.organization')),
            ],
        ),
    ]
