# Generated by Django 4.0.6 on 2022-08-10 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Devapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('when', models.TextField()),
                ('organizer', models.CharField(max_length=20)),
                ('location', models.TextField()),
                ('description', models.TextField()),
            ],
        ),
    ]
