# Generated by Django 3.2.7 on 2022-10-23 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Devapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancies',
            name='type_of',
            field=models.CharField(choices=[('USD', 'USD'), ('KGS', 'KGS'), ('RUB', 'RUB')], max_length=50, verbose_name='оклад'),
        ),
    ]
