# Generated by Django 3.2.7 on 2022-08-17 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Devapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vacancies',
            old_name='vacancies',
            new_name='organization',
        ),
    ]
