# Generated by Django 3.2.7 on 2022-10-23 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Devapp', '0002_alter_vacancies_type_of'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancies',
            name='type_of_2',
            field=models.CharField(default=1, max_length=50, verbose_name='оклад'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vacancies',
            name='type_of',
            field=models.CharField(choices=[('USD', 'USD'), ('KGS', 'KGS'), ('RUB', 'RUB')], max_length=50, verbose_name='валюта'),
        ),
    ]
