# Generated by Django 4.0.6 on 2022-08-10 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Devapp', '0002_events'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='events',
            options={'verbose_name': 'Мероприятие', 'verbose_name_plural': 'Мероприятия'},
        ),
    ]
