# Generated by Django 3.2.7 on 2022-08-17 08:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Devapp', '0003_remove_vacancies_organization'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Devapp.organization')),
            ],
        ),
        migrations.AddField(
            model_name='vacancies',
            name='vacancies',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Devapp.company'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='video',
            name='video1',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Devapp.company'),
            preserve_default=False,
        ),
    ]
