# Generated by Django 4.0.6 on 2022-08-11 18:32

import Devapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Devapp', '0004_alter_vacancies_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('date', models.CharField(max_length=50)),
                ('organization', models.CharField(max_length=50)),
                ('video', models.FileField(blank=True, null=True, upload_to=Devapp.models.upload_location)),
            ],
        ),
    ]
