# Generated by Django 3.2.7 on 2022-08-17 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Devapp', '0004_auto_20220817_0801'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vacancies',
            name='vacancies',
        ),
    ]
