# Generated by Django 3.2.7 on 2022-08-17 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Devapp', '0005_remove_vacancies_vacancies'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='events',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Devapp.company'),
            preserve_default=False,
        ),
    ]
