# Generated by Django 3.2.7 on 2022-08-17 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Devapp', '0006_events_events'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='events',
            name='events',
        ),
        migrations.AddField(
            model_name='company',
            name='events',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Devapp.events'),
            preserve_default=False,
        ),
    ]
