# Generated by Django 3.2.7 on 2022-08-17 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Devapp', '0007_auto_20220817_1155'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='video1',
        ),
        migrations.AddField(
            model_name='company',
            name='video',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Devapp.video'),
            preserve_default=False,
        ),
    ]
