# Generated by Django 3.2.7 on 2022-08-19 06:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Devapp', '0008_auto_20220817_1206'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='events',
        ),
        migrations.RemoveField(
            model_name='company',
            name='video',
        ),
        migrations.AddField(
            model_name='events',
            name='events',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='Devapp.company'),
            preserve_default=False,
        ),
    ]
