# Generated by Django 3.2.7 on 2022-08-19 07:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Devapp', '0010_alter_events_events'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='events',
            name='events',
        ),
        migrations.AddField(
            model_name='events',
            name='organization',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Devapp.organization'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vacancies',
            name='Organization',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Devapp.organization'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='video',
            name='organization1',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Devapp.organization'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Company',
        ),
    ]
