# Generated by Django 3.2.7 on 2022-08-19 08:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Devapp', '0011_auto_20220819_0706'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vacancies',
            old_name='Organization',
            new_name='organization',
        ),
        migrations.AlterField(
            model_name='events',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='org', to='Devapp.organization'),
        ),
    ]
