# Generated by Django 3.2.7 on 2022-08-19 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Devapp', '0012_auto_20220819_0827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Devapp.organization'),
        ),
        migrations.AlterField(
            model_name='vacancies',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacancia', to='Devapp.organization'),
        ),
    ]
