# Generated by Django 3.2.7 on 2022-08-24 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Devapp', '0014_auto_20220824_0403'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vacancies',
            options={'verbose_name': 'Вакансия', 'verbose_name_plural': 'Вакансии'},
        ),
        migrations.RenameField(
            model_name='vacancies',
            old_name='organization',
            new_name='organization2',
        ),
    ]
