# Generated by Django 3.2.7 on 2022-08-24 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Devapp', '0016_alter_video_video'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='date',
            new_name='publish_date',
        ),
        migrations.AlterField(
            model_name='video',
            name='organization',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
