# Generated by Django 3.2.7 on 2022-08-24 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Devapp', '0017_auto_20220824_0754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='organization',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='video',
            name='publish_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
