# Generated by Django 3.2.7 on 2022-08-24 08:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Devapp', '0018_auto_20220824_0756'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='video',
        ),
        migrations.AddField(
            model_name='video',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='video',
            name='published_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
