# Generated by Django 3.2.7 on 2022-08-25 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Devapp', '0020_auto_20220824_0805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='when',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
